const DEFAULT_HEADER = [
  '--------------------------------------------------------------------------------------------',
  'Generated by antigravity-cn-patch.',
  'Upstream VS Code localization files remain under their original license.',
  '--------------------------------------------------------------------------------------------'
];

export function countCoverage({ keys, upstream }) {
  const contents = upstream?.contents ?? {};
  let totalKeys = 0;
  let matchedKeys = 0;

  for (const [moduleName, moduleKeys] of keys) {
    const upstreamModule = contents[moduleName];
    for (const key of moduleKeys) {
      totalKeys += 1;
      if (upstreamModule && Object.prototype.hasOwnProperty.call(upstreamModule, key)) {
        matchedKeys += 1;
      }
    }
  }

  return {
    totalKeys,
    matchedKeys,
    missingKeys: totalKeys - matchedKeys,
    coveragePercent: totalKeys === 0 ? 100 : Number(((matchedKeys / totalKeys) * 100).toFixed(2))
  };
}

export function buildMainTranslation({
  keys,
  messages,
  upstream,
  overrides = {},
  allowFallback = true
}) {
  const upstreamContents = upstream?.contents ?? {};
  const contents = {};
  const missing = [];
  const stats = {
    totalKeys: 0,
    upstreamKeys: 0,
    overrideKeys: 0,
    fallbackKeys: 0,
    missingKeys: 0
  };

  let messageIndex = 0;
  for (const [moduleName, moduleKeys] of keys) {
    const outputModule = {};
    const upstreamModule = upstreamContents[moduleName] ?? {};
    const overrideModule = overrides[moduleName] ?? {};

    for (const key of moduleKeys) {
      const message = messages[messageIndex++];
      stats.totalKeys += 1;

      if (Object.prototype.hasOwnProperty.call(overrideModule, key)) {
        outputModule[key] = overrideModule[key];
        stats.overrideKeys += 1;
        continue;
      }

      if (Object.prototype.hasOwnProperty.call(upstreamModule, key)) {
        outputModule[key] = upstreamModule[key];
        stats.upstreamKeys += 1;
        continue;
      }

      const missingItem = {
        module: moduleName,
        key,
        message: normalizeMessage(message)
      };
      missing.push(missingItem);

      if (allowFallback) {
        outputModule[key] = fallbackTranslation(missingItem);
        stats.fallbackKeys += 1;
      }
    }

    if (Object.keys(outputModule).length > 0) {
      contents[moduleName] = outputModule;
    }
  }

  stats.missingKeys = missing.length;
  if (missing.length > 0 && !allowFallback) {
    const error = new Error(`Missing ${missing.length} translations`);
    error.missing = missing;
    throw error;
  }

  return {
    translation: {
      '': upstream?.[''] ?? DEFAULT_HEADER,
      version: upstream?.version ?? '1.0.0',
      contents
    },
    missing,
    stats
  };
}

export function fallbackTranslation({ module, key, message }) {
  const normalized = normalizeMessage(message);

  if (/^%[\w.-]+%$/.test(normalized)) {
    return placeholderName(normalized);
  }

  const byMessage = {
    Antigravity: 'Antigravity',
    Agent: 'Agent',
    IDE: 'IDE',
    Cancel: '取消',
    Close: '关闭',
    Configure: '配置',
    Continue: '继续',
    Restart: '重启',
    Retry: '重试',
    Settings: '设置',
    'Open Settings': '打开设置',
    'Open Agent Manager': '打开 Agent 管理器',
    'Manage Annotations': '管理注释',
    'Toggle Debug Info Widget': '切换调试信息小组件',
    'Explain and Fix Problem': '解释并修复问题',
    'Explain and Fix': '解释并修复',
    'Send Analytics': '发送分析数据',
    'Upload Error': '上传错误'
  };

  if (Object.prototype.hasOwnProperty.call(byMessage, normalized)) {
    return byMessage[normalized];
  }

  return `待补译项 ${shortStableId(`${module}/${key}`)}`;
}

function normalizeMessage(message) {
  if (typeof message === 'string') {
    return message;
  }
  if (message && typeof message === 'object' && typeof message.message === 'string') {
    return message.message;
  }
  return String(message ?? '');
}

function placeholderName(value) {
  const names = {
    '%colors.added%': '新增项颜色',
    '%colors.modified%': '修改项颜色',
    '%colors.deleted%': '删除项颜色',
    '%colors.untracked%': '未跟踪项颜色',
    '%colors.renamed%': '重命名项颜色',
    '%colors.ignored%': '忽略项颜色',
    '%colors.stageModified%': '暂存修改项颜色',
    '%colors.stageDeleted%': '暂存删除项颜色',
    '%colors.conflict%': '冲突项颜色',
    '%colors.submodule%': '子模块项颜色'
  };
  return names[value] ?? `待补译项 ${shortStableId(value)}`;
}

function shortStableId(value) {
  let hash = 0x811c9dc5;
  for (const char of String(value)) {
    hash ^= char.codePointAt(0);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(36).padStart(7, '0').slice(0, 7);
}
